### ISSUE TITLE
Oracle Transformation

### ISSUE THREAD

**Issue by WindFall-wyx** [Frankluox/Channel_Importance_FSL#1]
Hi, this is a solid and interesting work.
We try to reproduce Oracle Transformation following Eq(6) and F.1, but found that it may even drop 0.5% than the baseline. So could you release your Oracle Transformation code or show more details?
Thanks a lot.

**Comment by Frankluox** [comment]
Hi, thanks for your interest in our work! We will release the code today.

**Comment by Frankluox** [comment]
Hi, we have updated the code. The updated oracle transformation is an extended version of that in the ICML paper, additionally supporting features taking negative values. So you can test the transformation using any pre-trained backbones (like ResNet 12 with learkyReLU, CLIP, DINO, SwinTransformer, etc) to investigate the channel importance bias. Any further questions are welcome.

**Comment by WindFall-wyx** [comment]
Thanks for your prompt reply!
